# Generated by Django 5.0 on 2023-12-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('okunanlarid_user', models.IntegerField(blank=True, db_column='okunanlarID_user', null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoriler',
            fields=[
                ('favoriid', models.AutoField(db_column='favoriID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'FAVORILER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inceleme',
            fields=[
                ('incelemeid', models.AutoField(db_column='incelemeID', primary_key=True, serialize=False)),
                ('puan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'INCELEME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('kategoriid', models.AutoField(db_column='kategoriID', primary_key=True, serialize=False)),
                ('kategori', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'KATEGORI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('kitapid', models.AutoField(db_column='kitapID', primary_key=True, serialize=False)),
                ('kitapad', models.TextField(db_column='kitapAd')),
                ('yayintarihi', models.TextField(db_column='yayinTarihi')),
                ('sayfasayisi', models.IntegerField(db_column='sayfaSayisi')),
                ('dil', models.TextField()),
                ('ozet', models.TextField()),
            ],
            options={
                'db_table': 'KITAP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Okunacaklarlistesi',
            fields=[
                ('okunacaklarlistesiid', models.AutoField(db_column='okunacaklarListesiID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OKUNACAKLARLISTESI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Okunanlarlistesi',
            fields=[
                ('okunanlarlistesiid', models.AutoField(db_column='okunanlarListesiID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OKUNANLARLISTESI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yazarlar',
            fields=[
                ('yazarid', models.AutoField(db_column='yazarID', primary_key=True, serialize=False)),
                ('yazaradi', models.TextField(db_column='yazarAdi')),
                ('yazardogumtarihi', models.TextField(db_column='yazarDogumTarihi')),
                ('yazarbiyografi', models.TextField(db_column='yazarBiyografi')),
                ('yazarfoto', models.TextField(db_column='yazarFoto')),
                ('oduller', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'YAZARLAR',
                'managed': False,
            },
        ),
    ]
