# Generated by Django 5.0 on 2023-12-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitap',
            options={'managed': True},
        ),
    ]
