# Generated by Django 5.0 on 2023-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_alter_kitap_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='kategoriid_kitap',
            field=models.IntegerField(db_column='kategoriID_kitap', null=True),
        ),
        migrations.AddField(
            model_name='kitap',
            name='yazarid_kitap',
            field=models.IntegerField(db_column='yazarID_kitap', null=True),
        ),
    ]
