# Generated by Django 5.0 on 2023-12-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_kitap_kategoriid_kitap_kitap_yazarid_kitap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitap',
            options={'managed': False},
        ),
    ]
